
# 
# How to run 
# 
# All:        docker-compose up
# Single:     docker-compose run --service-ports rails
#             docker-compose stop rails1
# 

# 
# Strategy
# 
# 1. Setup config: docker-compose up
# 2. Update database: run database script
# 3. Start unicorn and sidekiq

# 
# XCO Project changes
# 
# database.yml
# searchkick.rb
# redis.rb
# snapstats.rb
# 

# 
# ENV VARIABLES
# 

# DOCKER_REDIS = address
# DOCER_ES = http://es:9200
# DOCKER_DB_HOST = db1
# DOCKER_DB_USER = root
# DOCKER_DB_PASS = '12345678'

# Docker
# http://code.tutsplus.com/tutorials/quick-tip-how-to-work-with-github-and-multiple-accounts--net-22574

# Restart
# docker kill `docker ps --no-trunc -aq` && docker rm `docker ps --no-trunc -aq`


rails:
  volumes:
    - /Users/kofee/Docker/rails:/rails
  ports:
    - "3000:8081"
  links:
    - es
    - db
    - redis
  environment:
    - RAILS_ENV=docker
    - DOCKER_REDIS=redis
    - DOCKER_ES=http://es:9200
    - DOCKER_DB_HOST=db
    - DOCKER_DB_USER=root
    - DOCKER_DB_PASS=12345678
  extends:
    file: rails/docker-compose.yml
    service: rails

es:
  volumes:
    - /Users/kofee/Docker/es:/es_data
    - /Users/kofee/Docker/es:/var/lib/mysql
  extends:
    file: es/docker-compose.yml
    service: es

db:
  volumes:
    - /Users/kofee/Docker/db:/db_dump
  ports:
    - "33006:3306"
  extends:
    file: db/docker-compose.yml
    service: db

redis:
  extends:
    file: redis/docker-compose.yml
    service: redis
