rails:
  image: xco/rails
  command: /bin/bash -l -c "bundle exec unicorn -p 8081"
  # command: /bin/bash -l -c "bundle exec rails c"
  # command: /bin/bash -l -c "cat /etc/hosts"
  # command: /bin/bash -l -c "bundle exec rails s"
  # command: /bin/bash -l -c "ping -c 1 db1"