rails:
  image: xco/rails
  command: /bin/bash -l -c "bundle exec unicorn -p 8081 -E docker -c config/unicorn_docker.rb"
  # command: /bin/bash -l -c "bundle exec unicorn -p 8081 -E docker"
  # command: /bin/bash -l -c "bundle exec rails c"
  # command: /bin/bash -l -c "cat /etc/hosts"
  # command: /bin/bash -l -c "RAILS_ENV=docker bundle exec rails s"
  # command: /bin/bash -l -c "ping -c 1 db1"

sidekiq:
	image: xco/rails
	command: /bin/bash -l -c "bundle exec sidekiq -c 25"
